# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled_xxxxx.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1368, 783)
        MainWindow.setStyleSheet("background-color: rgb(33, 97, 140);\n"
"")


        MainWindow.setWindowFlag(QtCore.Qt.FramelessWindowHint)


        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.drop_shadow_frame = QtWidgets.QFrame(self.centralwidget)
        self.drop_shadow_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.drop_shadow_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.drop_shadow_frame.setObjectName("drop_shadow_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.drop_shadow_frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.drop_shadow_frame)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frame_2.setStyleSheet("background-color: rgb(33, 97, 160);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_21 = QtWidgets.QFrame(self.frame_2)
        self.frame_21.setMaximumSize(QtCore.QSize(10, 16777215))
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.horizontalLayout.addWidget(self.frame_21)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_2.setContentsMargins(15, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 15pt \"Lucida Sans\";")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_3.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"  border: none;\n"
"  border-radius: 7px; \n"
"  background-color: rgb(85, 255, 127);\n"
"}\n"
"QPushButton:hover { \n"
"  background-color: rgba(85, 255, 127, 150);\n"
"}")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_2.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"  border: none;\n"
"  border-radius: 7px;   \n"
"  background-color: rgb(255, 170, 0);\n"
"}\n"
"QPushButton:hover { \n"
"  background-color: rgba(255, 170, 0, 150);\n"
"}")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.frame_5)
        self.pushButton.setMaximumSize(QtCore.QSize(15, 15))
        self.pushButton.setStyleSheet("QPushButton {\n"
"  border: none;\n"
"  border-radius: 7px;   \n"
"  background-color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:hover {   \n"
"  background-color: rgba(255, 0, 0, 150);\n"
"}")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.horizontalLayout.addWidget(self.frame_5)
        self.frame = QtWidgets.QFrame(self.frame_2)




        self.frame.setMinimumSize(QtCore.QSize(10, 35))
        self.frame.setMaximumSize(QtCore.QSize(10, 35))






        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.stackedWidget = QtWidgets.QStackedWidget(self.drop_shadow_frame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.page.setObjectName("page")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setSpacing(0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setSpacing(7)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        spacerItem1 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem1)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem2, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem3, 1, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem4, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("2020-08-08_012419.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout_14.addWidget(self.label_2, 0, 1, 1, 1)
        self.verticalLayout_18.addLayout(self.gridLayout_14)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_20.setContentsMargins(2, -1, 0, -1)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem5)
        self.lineEdit = QtWidgets.QLineEdit(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setStyleSheet("\n"
"border-radius: 10px;\n"
"font: 10pt \\\"Roboto\\\";\n"
"padding: 0 8px;\n"
"background: white;\n"
"selection-background-color: darkgray;\n"
"")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_20.addWidget(self.lineEdit)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem6)
        self.horizontalLayout_20.setStretch(0, 2)
        self.horizontalLayout_20.setStretch(1, 5)
        self.verticalLayout_20.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setContentsMargins(22, 5, 9, 12)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem7)
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("2020-08-08_004209.png"))
        self.label_3.setScaledContents(False)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_21.addWidget(self.label_3)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem8)
        self.horizontalLayout_21.setStretch(0, 1)
        self.horizontalLayout_21.setStretch(1, 2)
        self.horizontalLayout_21.setStretch(2, 1)
        self.verticalLayout_20.addLayout(self.horizontalLayout_21)
        self.verticalLayout_19.addLayout(self.verticalLayout_20)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setContentsMargins(18, -1, 30, 12)
        self.horizontalLayout_22.setSpacing(7)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem9)
        self.pushButton_6 = QtWidgets.QPushButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setStyleSheet("\n"
"QPushButton{\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 8px;\n"
"padding: 0 8px;\n"
"background: white;\n"
"selection-background-color: darkgray;\n"
"background-color: rgb(39, 92, 189);\n"
"color: white;\n"
"font: 10pt \"Roboto\";\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: ipx solid #828282;\n"
"background-color: rgb(39, 92, 222);\n"
"}\n"
"QPushButton:hover:pressed{\n"
"border: 2px solid gray;\n"
"font: 8pt \"Roboto\";\n"
"border-radius: 8px;\n"
"padding: 0 8px;\n"
"background: gray;\n"
"selection-background-color: darkgray;\n"
"background-color: gray;\n"
"\n"
"color: white;\n"
"font: 11pt \"Roboto\";\n"
"background-image: -webkit-linear-gradient(top, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.2));\n"
"background-image: -moz-linear-gradient(top, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.2));\n"
"background-image: -o-linear-gradient(top, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.2));\n"
"background-image: -ms-linear-gradient(top, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.2));\n"
"background-image: linear-gradient(top, rgba(0, 0, 0, 0), rgba(0, 0, 0, 0.2));\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_22.addWidget(self.pushButton_6)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem10)
        self.label_8 = QtWidgets.QLabel(self.page)
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("2020-08-24_102511.png"))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_22.addWidget(self.label_8)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem11)
        self.horizontalLayout_22.setStretch(0, 2)
        self.horizontalLayout_22.setStretch(1, 3)
        self.horizontalLayout_22.setStretch(3, 1)
        self.horizontalLayout_22.setStretch(4, 1)
        self.verticalLayout_22.addLayout(self.horizontalLayout_22)
        self.verticalLayout_21.addLayout(self.verticalLayout_22)
        self.verticalLayout_19.addLayout(self.verticalLayout_21)
        self.verticalLayout_18.addLayout(self.verticalLayout_19)
        self.verticalLayout_17.addLayout(self.verticalLayout_18)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setContentsMargins(-1, 7, 0, 0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem12, 0, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem13, 1, 0, 1, 1)
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_23.setSpacing(15)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.pushButton_12 = QtWidgets.QPushButton(self.page)
        self.pushButton_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"font: 9pt \\\"Lucida Sans\\\";\n"
"color: rgb(68, 118, 179);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: ipx solid #828282;\n"
"color: rgb(20, 120, 250);\n"
"}\n"
"\n"
"QPushButton:hover:pressed{\n"
"background-color: rgb(255, 255, 255);\n"
"font: 9pt \\\"Lucida Sans\\\";\n"
"\n"
"\n"
"color: black;\n"
"border-radius: 10px;\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_23.addWidget(self.pushButton_12)

        self.gridLayout_15.addLayout(self.verticalLayout_23, 1, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem14, 1, 2, 1, 1)
        self.verticalLayout_17.addLayout(self.gridLayout_15)
        self.verticalLayout_16.addLayout(self.verticalLayout_17)
        spacerItem15 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem15)
        self.horizontalLayout_17.addLayout(self.verticalLayout_16)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem16)
        self.horizontalLayout_17.setStretch(0, 1)
        self.horizontalLayout_17.setStretch(2, 1)
        self.gridLayout_16.addLayout(self.horizontalLayout_17, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setSpacing(0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.page_2)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 45))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setMaximumSize(QtCore.QSize(360, 16777215))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setContentsMargins(0, 7, 0, 4)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_18 = QtWidgets.QFrame(self.frame_6)
        self.frame_18.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_18.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_18)
        self.pushButton_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px solid;")
        icon_3 = QtGui.QIcon()
        icon_3.addPixmap(QtGui.QPixmap("lock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon_3)
        self.pushButton_5.setIconSize(QtCore.QSize(25, 25)) 
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_9.addWidget(self.pushButton_5)
        self.horizontalLayout_4.addWidget(self.frame_18)
        self.frame_19 = QtWidgets.QFrame(self.frame_6)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.textEdit_2 = QtWidgets.QTextEdit(self.frame_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_2.sizePolicy().hasHeightForWidth())
        self.textEdit_2.setSizePolicy(sizePolicy)
        self.textEdit_2.setMinimumSize(QtCore.QSize(100, 30))
        self.textEdit_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 11pt \"Lucida Sans\";\n"
"border-radius: 3px;\n"
"")
        self.textEdit_2.setObjectName("textEdit_2")

        self.textEdit_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)


        self.horizontalLayout_10.addWidget(self.textEdit_2)
        self.horizontalLayout_4.addWidget(self.frame_19)
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_6.setContentsMargins(50, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setStyleSheet("border-radius: 10px;\n"
"color: rgb(255, 255, 255);\n"
"font: 20pt \"Lucida Sans\";")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.horizontalLayout_5.addWidget(self.frame_8)
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_5.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.frame_7)
        self.frame_10.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_5.addWidget(self.frame_10)
        self.horizontalLayout_3.addWidget(self.frame_7)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.frame_11 = QtWidgets.QFrame(self.page_2)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setSpacing(0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_11)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_12 = QtWidgets.QFrame(self.page_4)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_13 = QtWidgets.QFrame(self.frame_12)
        self.frame_13.setMaximumSize(QtCore.QSize(360, 16777215))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.frame_13)
        self.scrollArea_2.setStyleSheet("background-color: rgb(216, 240, 255);\n"
        "border: none;\n")



        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
#######
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)






        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 356, 694))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollAreaWidgetContents_2.setStyleSheet("border: none;\n")
        


        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        
        



        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.addWidget(self.scrollArea_2)
        self.horizontalLayout_13.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(self.frame_12)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_15 = QtWidgets.QFrame(self.frame_14)
        self.frame_15.setStyleSheet("border-radius: 10px;")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_15)
        self.scrollArea.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
#######
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)


        bar = self.scrollArea.verticalScrollBar() 
        bar.rangeChanged.connect(lambda x,y: bar.setValue(9999)) 


######
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 859, 631))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")



#############################
        self.verticalLayout_41 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.verticalLayout_41.setSpacing(33)












        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_8.addWidget(self.scrollArea)
        self.verticalLayout_7.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(self.frame_14)
        self.frame_16.setMaximumSize(QtCore.QSize(16777215, 65))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame_17 = QtWidgets.QFrame(self.frame_16)
        self.frame_17.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_16.setContentsMargins(11, 7, 5, 7)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")


        self.pushButton_15 = QtWidgets.QPushButton(self.frame_17)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_15.sizePolicy().hasHeightForWidth())
        self.pushButton_15.setSizePolicy(sizePolicy)
        self.pushButton_15.setStyleSheet("")
        self.pushButton_15.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("wlt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_15.setIcon(icon)
        self.pushButton_15.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_15.setCheckable(False)
        self.pushButton_15.setAutoRepeat(False)
        self.pushButton_15.setAutoExclusive(False)
        self.pushButton_15.setDefault(False)
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_15.setStyleSheet("border: none;")
        self.horizontalLayout_16.addWidget(self.pushButton_15)
        self.horizontalLayout_16.addWidget(self.pushButton_15)



        self.textEdit = QtWidgets.QTextEdit(self.frame_17)
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Lucida Sans\";\n"
"border-radius: 10px;")
        self.textEdit.setObjectName("textEdit")



        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
       # self.textEdit.setPlaceholderText("Write and press ALT to send a message...")
        self.textEdit.setPlaceholderText("Select_user. . . ")




        self.horizontalLayout_16.addWidget(self.textEdit)
        self.horizontalLayout_14.addWidget(self.frame_17)
        self.frame_20 = QtWidgets.QFrame(self.frame_16)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_20.sizePolicy().hasHeightForWidth())
        self.frame_20.setSizePolicy(sizePolicy)
        self.frame_20.setMaximumSize(QtCore.QSize(80, 16777215))
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_15.setContentsMargins(10, 7, 15, 7)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_20)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setStyleSheet("")
        self.pushButton_4.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("2020-08-24_152554.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_4.setCheckable(False)
        self.pushButton_4.setAutoRepeat(False)
        self.pushButton_4.setAutoExclusive(False)
        self.pushButton_4.setDefault(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"border: none\n"
"}\n")
        self.horizontalLayout_15.addWidget(self.pushButton_4)
        self.horizontalLayout_14.addWidget(self.frame_20)
        self.frame_22 = QtWidgets.QFrame(self.frame_16)
        self.frame_22.setMinimumSize(QtCore.QSize(6, 65))
        self.frame_22.setMaximumSize(QtCore.QSize(6, 65))
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.horizontalLayout_14.addWidget(self.frame_22)
        self.verticalLayout_7.addWidget(self.frame_16)
        self.horizontalLayout_13.addWidget(self.frame_14)
        self.gridLayout_3.addWidget(self.frame_12, 0, 0, 1, 1)
        self.stackedWidget_2.addWidget(self.page_4)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.page_6.setObjectName("page_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_24.setContentsMargins(0, 41, 0, 0)
        self.verticalLayout_24.setSpacing(9)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setContentsMargins(59, -1, 265, -1)
        self.verticalLayout_25.setSpacing(18)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.pushButton_14 = QtWidgets.QPushButton(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        self.pushButton_14.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_14.setStyleSheet("QPushButton{\n"
"    font: 14pt \"Lucida Sans\";\n"
"background-color: rgb(255, 255, 255);\n"
"font: 14pt \\\"Lucida Sans\\\";\n"
"color: rgb(68, 118, 179);\n"
"border-radius: 10px;\n"

"}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_25.addWidget(self.pushButton_14)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem17)
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setContentsMargins(46, -1, -1, -1)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setSpacing(0)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.label_4 = QtWidgets.QLabel(self.page_6)
        self.label_4.setStyleSheet("font: 12pt \"Lucida Sans\";")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_34.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.page_6)
        self.label_5.setMaximumSize(QtCore.QSize(400, 30))
        self.label_5.setStyleSheet("font: 11pt \"Lucida Sans\";")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_34.addWidget(self.label_5)
        self.verticalLayout_33.addLayout(self.verticalLayout_34)
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setSpacing(0)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.label_10 = QtWidgets.QLabel(self.page_6)
        self.label_10.setStyleSheet("font: 12pt \"Lucida Sans\";")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_35.addWidget(self.label_10)
        self.label_15 = QtWidgets.QLabel(self.page_6)
        self.label_15.setMaximumSize(QtCore.QSize(150, 30))
        self.label_15.setStyleSheet("font: 11pt \"Lucida Sans\";\n"
"  background-color: rgb(85, 255, 127);")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_35.addWidget(self.label_15)
        self.verticalLayout_33.addLayout(self.verticalLayout_35)
        self.verticalLayout_32.addLayout(self.verticalLayout_33)
        self.horizontalLayout_12.addLayout(self.verticalLayout_32)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem18)
        self.verticalLayout_25.addLayout(self.horizontalLayout_12)
        self.verticalLayout_24.addLayout(self.verticalLayout_25)
        self.pushButton_17 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_17.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_17.setAutoFillBackground(False)
        self.pushButton_17.setStyleSheet("QPushButton{\n"
"    font: 14pt \"Lucida Sans\";\n"
"background-color: rgb(255, 255, 255);\n"
"font: 14pt \\\"Lucida Sans\\\";\n"
"color: rgb(68, 118, 179);\n"
"border-radius: 10px;\n"

"}")
        self.pushButton_17.setObjectName("pushButton_17")
        self.verticalLayout_24.addWidget(self.pushButton_17)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setSpacing(0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem19)
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setContentsMargins(0, 28, 92, -1)
        self.verticalLayout_31.setSpacing(43)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.pushButton_19 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_19.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"font: 11pt \\\"Lucida Sans\\\";\n"
"color: rgb(68, 118, 179);\n"
"border-radius: 10px;\n"
"}")
        self.pushButton_19.setObjectName("pushButton_19")
        self.verticalLayout_31.addWidget(self.pushButton_19)
     

        self.line_coin = QtWidgets.QLineEdit(self.page_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.line_coin.sizePolicy().hasHeightForWidth())
        self.line_coin.setSizePolicy(sizePolicy)
        self.line_coin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_coin.setAutoFillBackground(False)
        self.line_coin.setStyleSheet("\n"
"border-radius: 10px;\n"
"padding: 0 8px;\n"
"background: white;\n"
"selection-background-color: darkgray;\n"
"")
       # self.line_coin.setText('должен быть кошелек отправляющего')
        self.line_coin.setPlaceholderText(" amount. . .")
        self.line_coin.setObjectName("line_coin")





        self.verticalLayout_31.addWidget(self.line_coin)
        self.pushButton_21 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_21.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"font: 11pt \\\"Lucida Sans\\\";\n"
"color: rgb(68, 118, 179);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: ipx solid #828282;\n"
"color: rgb(20, 120, 250);\n"
"}\n"
"\n"
"QPushButton:hover:pressed{\n"
"background-color: rgb(255, 255, 255);\n"
"font: 9pt \\\"Lucida Sans\\\";\n"
"\n"
"\n"
"color: black;\n"
"border-radius: 10px;\n"
"}")
        self.pushButton_21.setObjectName("pushButton_21")
        self.verticalLayout_31.addWidget(self.pushButton_21)
        self.horizontalLayout_24.addLayout(self.verticalLayout_31)
        self.horizontalLayout_24.setStretch(0, 1)
        self.verticalLayout_24.addLayout(self.horizontalLayout_24)
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setContentsMargins(-1, -1, 265, -1)
        self.verticalLayout_30.setSpacing(18)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_30.addItem(spacerItem20)
        self.verticalLayout_24.addLayout(self.verticalLayout_30)
        self.verticalLayout_24.setStretch(0, 1)
        self.verticalLayout_24.setStretch(2, 1)
        self.verticalLayout_24.setStretch(3, 1)
        self.horizontalLayout_23.addLayout(self.verticalLayout_24)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem21)
        self.horizontalLayout_23.setStretch(0, 1)
        self.horizontalLayout_23.setStretch(1, 6)
        self.gridLayout_6.addLayout(self.horizontalLayout_23, 0, 0, 1, 1)
        self.stackedWidget_2.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.page_7.setObjectName("page_7")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_7)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_9.setContentsMargins(0, 41, 0, 0)
        self.verticalLayout_9.setSpacing(9)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setContentsMargins(-1, -1, 265, -1)
        self.verticalLayout_10.setSpacing(18)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.pushButton_9 = QtWidgets.QPushButton(self.page_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"    font: 10pt \"Lucida Sans\";\n"
"background-color: rgb(255, 255, 255);\n"
"font: 10pt \\\"Lucida Sans\\\";\n"
"color: rgb(68, 118, 179);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: ipx solid #828282;\n"
"color: rgb(20, 120, 250);\n"
"}\n"
"\n"
"QPushButton:hover:pressed{\n"
"background-color: rgb(255, 255, 255);\n"
"font: 9pt \\\"Lucida Sans\\\";\n"
"\n"
"\n"
"color: black;\n"
"border-radius: 10px;\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_10.addWidget(self.pushButton_9)
        self.pushButton_7 = QtWidgets.QPushButton(self.page_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"    font: 10pt \"Lucida Sans\";\n"
"background-color: rgb(255, 255, 255);\n"
"font: 10pt \\\"Lucida Sans\\\";\n"
"color: rgb(68, 118, 179);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: ipx solid #828282;\n"
"color: rgb(20, 120, 250);\n"
"}\n"
"\n"
"QPushButton:hover:pressed{\n"
"background-color: rgb(255, 255, 255);\n"
"font: 9pt \\\"Lucida Sans\\\";\n"
"\n"
"\n"
"color: black;\n"
"border-radius: 10px;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_10.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.page_7)
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"font: 10pt \\\"Lucida Sans\\\";\n"
"color: rgb(68, 118, 179);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: ipx solid #828282;\n"
"color: rgb(20, 120, 250);\n"
"}\n"
"\n"
"QPushButton:hover:pressed{\n"
"background-color: rgb(255, 255, 255);\n"
"font: 9pt \\\"Lucida Sans\\\";\n"
"\n"
"\n"
"color: black;\n"
"border-radius: 10px;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_10.addWidget(self.pushButton_8)
        self.verticalLayout_9.addLayout(self.verticalLayout_10)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem22)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_11.setContentsMargins(77, -1, -1, -1)
        self.verticalLayout_11.setSpacing(26)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSpacing(10)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.checkBox = QtWidgets.QCheckBox(self.page_7)
        self.checkBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \\\"Lucida Sans\\\";\n"
"color: rgb(68, 118, 179);\n"
"border-radius: 10px;")
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_12.addWidget(self.checkBox)
        self.label_6 = QtWidgets.QLabel(self.page_7)
        self.label_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \\\"Lucida Sans\\\";\n"
"color: rgb(68, 118, 179);\n"
"border-radius: 10px;")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_12.addWidget(self.label_6)
        self.verticalLayout_11.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSpacing(10)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.checkBox_2 = QtWidgets.QCheckBox(self.page_7)
        self.checkBox_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \\\"Lucida Sans\\\";\n"
"color: rgb(68, 118, 179);\n"
"border-radius: 10px;")
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_13.addWidget(self.checkBox_2)
        self.label_9 = QtWidgets.QLabel(self.page_7)
        self.label_9.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \\\"Lucida Sans\\\";\n"
"color: rgb(68, 118, 179);\n"
"border-radius: 10px;")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_13.addWidget(self.label_9)
        self.verticalLayout_11.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setSpacing(10)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.checkBox_3 = QtWidgets.QCheckBox(self.page_7)
        self.checkBox_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \\\"Lucida Sans\\\";\n"
"color: rgb(68, 118, 179);\n"
"border-radius: 10px;\n"
"")
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_14.addWidget(self.checkBox_3)
        self.label_11 = QtWidgets.QLabel(self.page_7)
        self.label_11.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \\\"Lucida Sans\\\";\n"
"color: rgb(68, 118, 179);\n"
"border-radius: 10px;")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_14.addWidget(self.label_11)
        self.verticalLayout_11.addLayout(self.verticalLayout_14)
        self.horizontalLayout_19.addLayout(self.verticalLayout_11)
        self.horizontalLayout_19.setStretch(0, 1)
        self.horizontalLayout_19.setStretch(1, 10)
        self.verticalLayout_9.addLayout(self.horizontalLayout_19)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setContentsMargins(-1, -1, 265, -1)
        self.verticalLayout_15.setSpacing(18)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.pushButton_10 = QtWidgets.QPushButton(self.page_7)
        self.pushButton_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_10.setAutoFillBackground(False)
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"font: 10pt \\\"Lucida Sans\\\";\n"
"color: rgb(68, 118, 179);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: ipx solid #828282;\n"
"color: rgb(20, 120, 250);\n"
"}\n"
"\n"
"QPushButton:hover:pressed{\n"
"background-color: rgb(255, 255, 255);\n"
"font: 9pt \\\"Lucida Sans\\\";\n"
"\n"
"\n"
"color: black;\n"
"border-radius: 10px;\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_15.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.page_7)
        self.pushButton_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 255, 255);\n"
"font: 11pt \\\"Lucida Sans\\\";\n"
"color: rgb(68, 118, 179);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"border: ipx solid #828282;\n"
"color: rgb(20, 120, 250);\n"
"}\n"
"\n"
"QPushButton:hover:pressed{\n"
"background-color: rgb(255, 255, 255);\n"
"font: 9pt \\\"Lucida Sans\\\";\n"
"\n"
"\n"
"color: black;\n"
"border-radius: 10px;\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_15.addWidget(self.pushButton_11)
        self.verticalLayout_9.addLayout(self.verticalLayout_15)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem23)
        self.verticalLayout_9.setStretch(0, 1)
        self.verticalLayout_9.setStretch(1, 1)
        self.verticalLayout_9.setStretch(2, 1)
        self.verticalLayout_9.setStretch(3, 1)
        self.horizontalLayout_18.addLayout(self.verticalLayout_9)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem24)
        self.horizontalLayout_18.setStretch(0, 1)
        self.horizontalLayout_18.setStretch(1, 6)
        
        self.stackedWidget_2.addWidget(self.page_7)
        self.gridLayout_12.addWidget(self.stackedWidget_2, 0, 1, 1, 1)


        self.page_8 = QtWidgets.QWidget()
        self.page_8.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.page_8.setObjectName("page_8")


        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_8)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")

        
        self.кнопка_добавл = QtWidgets.QPushButton(self.page_8)
        self.кнопка_добавл.setGeometry(QtCore.QRect(120, 250, 181, 41))
        self.кнопка_добавл.setObjectName("кнопка_добавл")
        self.ввод_имени_польз = QtWidgets.QLineEdit(self.page_8)
        self.ввод_имени_польз.setGeometry(QtCore.QRect(120, 100, 201, 31))
        self.ввод_имени_польз.setObjectName("ввод_имени_польз")
        self.label_имени_польз = QtWidgets.QLabel(self.page_8)
        self.label_имени_польз.setGeometry(QtCore.QRect(120, 60, 261, 31))
        self.label_имени_польз.setObjectName("label_имени_польз")
        self.label_кошелек_польз = QtWidgets.QLabel(self.page_8)
        self.label_кошелек_польз.setGeometry(QtCore.QRect(130, 150, 211, 21))
        self.label_кошелек_польз.setObjectName("label_кошелек_польз")
        self.lineEdit_кошелька = QtWidgets.QLineEdit(self.page_8)
        self.lineEdit_кошелька.setGeometry(QtCore.QRect(120, 190, 201, 31))
        self.lineEdit_кошелька.setObjectName("lineEdit_кошелька")
        self.label_статус = QtWidgets.QLabel(self.page_8)
        self.label_статус.setGeometry(QtCore.QRect(430, 110, 371, 61))
        self.label_статус.setObjectName("label_статус")
        self.кнопка_добавл.setText("Добавить")
        self.label_имени_польз.setText("введите имя пользователя(по выбору)")
        self.label_кошелек_польз.setText("введите кошелек пользователя")
        self.label_статус.setText("статус (добавлен или нет; надпись изменим)")
        self.stackedWidget.addWidget(self.page_8)





        self.stackedWidget_2.addWidget(self.page_8)


















        self.frame_left_menu = QtWidgets.QFrame(self.frame_11)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_left_menu.setStyleSheet("background-color: rgb(33, 97, 160);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.frame_top_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_top_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menus.setObjectName("frame_top_menus")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setSpacing(0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.btn_page_1 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_1.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_1.setStyleSheet("QPushButton {\n"
"  color: rgb(255, 255, 255);\n"
"  background-color: rgb(33, 97, 160);\n"
"  border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"  background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_page_1.setObjectName("btn_page_1")
        self.verticalLayout_27.addWidget(self.btn_page_1)
        self.btn_page_2 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_2.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_2.setStyleSheet("QPushButton {\n"
"  color: rgb(255, 255, 255);\n"
"  background-color: rgb(33, 97, 160);\n"
"  border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"  background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_page_2.setObjectName("btn_page_2")
        self.verticalLayout_27.addWidget(self.btn_page_2)
     #   self.btn_page_3 = QtWidgets.QPushButton(self.frame_top_menus)
     #   self.btn_page_3.setMinimumSize(QtCore.QSize(0, 40))
     #  self.btn_page_3.setStyleSheet("QPushButton {\n"
#"  color: rgb(255, 255, 255);\n"
#"  background-color: rgb(33, 97, 160);\n"
#"  border: 0px solid;\n"
#"}\n"
#"QPushButton:hover {\n"
#"  background-color: rgb(85, 170, 255);\n"
#"}")
#        self.btn_page_3.setObjectName("btn_page_3")
#        self.verticalLayout_27.addWidget(self.btn_page_3)

        self.btn_page_4 = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_page_4.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_page_4.setStyleSheet("QPushButton {\n"
"  color: rgb(255, 255, 255);\n"
"  background-color: rgb(33, 97, 160);\n"
"  border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"  background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_page_4.setObjectName("btn_page_4")
        self.verticalLayout_27.addWidget(self.btn_page_4)




        self.verticalLayout_26.addWidget(self.frame_top_menus, 0, QtCore.Qt.AlignTop)
        self.gridLayout_12.addWidget(self.frame_left_menu, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.frame_11)
        self.gridLayout_13.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.drop_shadow_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stackedWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "VerBium"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", " Enter your local password. . ."))
        self.pushButton_6.setText(_translate("MainWindow", "LOGIN"))
        self.pushButton_12.setText(_translate("MainWindow", "Or create a new anonymous addres"))
        
        self.textEdit_2.setPlaceholderText(_translate("MainWindow", " Search"))
       
        self.textEdit.setPlaceholderText(_translate("MainWindow", "Select_user. . ."))
        self.pushButton_14.setText(_translate("MainWindow", "Данные кошелька           "))
        self.label_4.setText(_translate("MainWindow", "VERBIUM КОШЕЛЕК:"))
        self.label_5.setText(_translate("MainWindow", ""))
        self.label_10.setText(_translate("MainWindow", "БАЛАНС:"))
        self.label_15.setText(_translate("MainWindow", ""))
        self.pushButton_17.setText(_translate("MainWindow", "Отправить  пользователю:                          "))
        self.pushButton_19.setText(_translate("MainWindow", "по умолчанию должен быть кошелек получающего        "))
     #   self.pushButton_20.setText(_translate("MainWindow", "Купить и продать токены             "))
        self.pushButton_21.setText(_translate("MainWindow", "Отправить "))
        self.pushButton_9.setText(_translate("MainWindow", "Общая информация           "))
        self.pushButton_7.setText(_translate("MainWindow", " Безопасность и вход           "))
        self.pushButton_8.setText(_translate("MainWindow", "Уведомления:                    "))
        self.checkBox.setText(_translate("MainWindow", "Звук"))
        self.label_6.setText(_translate("MainWindow", "Воспроизведение звука при поучении нового сообщения"))
        self.checkBox_2.setText(_translate("MainWindow", "Счетчик новых сообщений"))
        self.label_9.setText(_translate("MainWindow", "Показывает счетчик сообщений в заголовке новой вкладке"))
        self.checkBox_3.setText(_translate("MainWindow", "Push-уведомления"))
        self.label_11.setText(_translate("MainWindow", "Уведомления на рабочем столе. Требуется разрешение"))
        self.pushButton_10.setText(_translate("MainWindow", "Отправить:                          "))
        self.pushButton_11.setText(_translate("MainWindow", "Выход             "))
        self.btn_page_1.setText(_translate("MainWindow", "Сообщения"))
        self.btn_page_2.setText(_translate("MainWindow", "Настройки"))
     #   self.btn_page_3.setText(_translate("MainWindow", "send"))
        self.btn_page_4.setText(_translate("MainWindow", "Добавить\nконтакт"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
